package theme.color_palettes

import androidx.compose.ui.graphics.Color
import theme.MaterialThemeColorsPalette

object GreenColorBase : MaterialThemeColorsPalette {
    override val primaryLight : Color = Color(0xFF4C662B)
    override val onPrimaryLight : Color = Color(0xFFFFFFFF)
    override val primaryContainerLight : Color = Color(0xFFCDEDA3)
    override val onPrimaryContainerLight : Color = Color(0xFF102000)
    override val secondaryLight : Color = Color(0xFF586249)
    override val onSecondaryLight : Color = Color(0xFFFFFFFF)
    override val secondaryContainerLight : Color = Color(0xFFDCE7C8)
    override val onSecondaryContainerLight : Color = Color(0xFF151E0B)
    override val tertiaryLight : Color = Color(0xFF386663)
    override val onTertiaryLight : Color = Color(0xFFFFFFFF)
    override val tertiaryContainerLight : Color = Color(0xFFBCECE7)
    override val onTertiaryContainerLight : Color = Color(0xFF00201E)
    override val errorLight : Color = Color(0xFFBA1A1A)
    override val onErrorLight : Color = Color(0xFFFFFFFF)
    override val errorContainerLight : Color = Color(0xFFFFDAD6)
    override val onErrorContainerLight : Color = Color(0xFF410002)
    override val backgroundLight : Color = Color(0xFFF9FAEF)
    override val onBackgroundLight : Color = Color(0xFF1A1C16)
    override val surfaceLight : Color = Color(0xFFF9FAEF)
    override val onSurfaceLight : Color = Color(0xFF1A1C16)
    override val surfaceVariantLight : Color = Color(0xFFE1E4D5)
    override val onSurfaceVariantLight : Color = Color(0xFF44483D)
    override val outlineLight : Color = Color(0xFF75796C)
    override val outlineVariantLight : Color = Color(0xFFC5C8BA)
    override val scrimLight : Color = Color(0xFF000000)
    override val inverseSurfaceLight : Color = Color(0xFF2F312A)
    override val inverseOnSurfaceLight : Color = Color(0xFFF1F2E6)
    override val inversePrimaryLight : Color = Color(0xFFB1D18A)
    override val surfaceDimLight : Color = Color(0xFFDADBD0)
    override val surfaceBrightLight : Color = Color(0xFFF9FAEF)
    override val surfaceContainerLowestLight : Color = Color(0xFFFFFFFF)
    override val surfaceContainerLowLight : Color = Color(0xFFF3F4E9)
    override val surfaceContainerLight : Color = Color(0xFFEEEFE3)
    override val surfaceContainerHighLight : Color = Color(0xFFE8E9DE)
    override val surfaceContainerHighestLight : Color = Color(0xFFE2E3D8)

    override val primaryDark : Color = Color(0xFFB1D18A)
    override val onPrimaryDark : Color = Color(0xFF1F3701)
    override val primaryContainerDark : Color = Color(0xFF354E16)
    override val onPrimaryContainerDark : Color = Color(0xFFCDEDA3)
    override val secondaryDark : Color = Color(0xFFBFCBAD)
    override val onSecondaryDark : Color = Color(0xFF2A331E)
    override val secondaryContainerDark : Color = Color(0xFF404A33)
    override val onSecondaryContainerDark : Color = Color(0xFFDCE7C8)
    override val tertiaryDark : Color = Color(0xFFA0D0CB)
    override val onTertiaryDark : Color = Color(0xFF003735)
    override val tertiaryContainerDark : Color = Color(0xFF1F4E4B)
    override val onTertiaryContainerDark : Color = Color(0xFFBCECE7)
    override val errorDark : Color = Color(0xFFFFB4AB)
    override val onErrorDark : Color = Color(0xFF690005)
    override val errorContainerDark : Color = Color(0xFF93000A)
    override val onErrorContainerDark : Color = Color(0xFFFFDAD6)
    override val backgroundDark : Color = Color(0xFF12140E)
    override val onBackgroundDark : Color = Color(0xFFE2E3D8)
    override val surfaceDark : Color = Color(0xFF12140E)
    override val onSurfaceDark : Color = Color(0xFFE2E3D8)
    override val surfaceVariantDark : Color = Color(0xFF44483D)
    override val onSurfaceVariantDark : Color = Color(0xFFC5C8BA)
    override val outlineDark : Color = Color(0xFF8F9285)
    override val outlineVariantDark : Color = Color(0xFF44483D)
    override val scrimDark : Color = Color(0xFF000000)
    override val inverseSurfaceDark : Color = Color(0xFFE2E3D8)
    override val inverseOnSurfaceDark : Color = Color(0xFF2F312A)
    override val inversePrimaryDark : Color = Color(0xFF4C662B)
    override val surfaceDimDark : Color = Color(0xFF12140E)
    override val surfaceBrightDark : Color = Color(0xFF383A32)
    override val surfaceContainerLowestDark : Color = Color(0xFF0C0F09)
    override val surfaceContainerLowDark : Color = Color(0xFF1A1C16)
    override val surfaceContainerDark : Color = Color(0xFF1E201A)
    override val surfaceContainerHighDark : Color = Color(0xFF282B24)
    override val surfaceContainerHighestDark : Color = Color(0xFF33362E)
}