package theme

import androidx.compose.ui.graphics.Color

interface MaterialThemeColorsPalette {
    val primaryLight: Color
    val onPrimaryLight: Color
    val primaryContainerLight: Color
    val onPrimaryContainerLight: Color
    val secondaryLight: Color
    val onSecondaryLight: Color
    val secondaryContainerLight: Color
    val onSecondaryContainerLight: Color
    val tertiaryLight: Color
    val onTertiaryLight: Color
    val tertiaryContainerLight: Color
    val onTertiaryContainerLight: Color
    val errorLight: Color
    val onErrorLight: Color
    val errorContainerLight: Color
    val onErrorContainerLight: Color
    val backgroundLight: Color
    val onBackgroundLight: Color
    val surfaceLight: Color
    val onSurfaceLight: Color
    val surfaceVariantLight: Color
    val onSurfaceVariantLight: Color
    val outlineLight: Color
    val outlineVariantLight: Color
    val scrimLight: Color
    val inverseSurfaceLight: Color
    val inverseOnSurfaceLight: Color
    val inversePrimaryLight: Color
    val surfaceDimLight: Color
    val surfaceBrightLight: Color
    val surfaceContainerLowestLight: Color
    val surfaceContainerLowLight: Color
    val surfaceContainerLight: Color
    val surfaceContainerHighLight: Color
    val surfaceContainerHighestLight: Color

    val primaryDark: Color
    val onPrimaryDark: Color
    val primaryContainerDark: Color
    val onPrimaryContainerDark: Color
    val secondaryDark: Color
    val onSecondaryDark: Color
    val secondaryContainerDark: Color
    val onSecondaryContainerDark: Color
    val tertiaryDark: Color
    val onTertiaryDark: Color
    val tertiaryContainerDark: Color
    val onTertiaryContainerDark: Color
    val errorDark: Color
    val onErrorDark: Color
    val errorContainerDark: Color
    val onErrorContainerDark: Color
    val backgroundDark: Color
    val onBackgroundDark: Color
    val surfaceDark: Color
    val onSurfaceDark: Color
    val surfaceVariantDark: Color
    val onSurfaceVariantDark: Color
    val outlineDark: Color
    val outlineVariantDark: Color
    val scrimDark: Color
    val inverseSurfaceDark: Color
    val inverseOnSurfaceDark: Color
    val inversePrimaryDark: Color
    val surfaceDimDark: Color
    val surfaceBrightDark: Color
    val surfaceContainerLowestDark: Color
    val surfaceContainerLowDark: Color
    val surfaceContainerDark: Color
    val surfaceContainerHighDark: Color
    val surfaceContainerHighestDark: Color
}